### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by AEstein** [amanshenoy/ray-tracer#3]
Hi, when I run the test case for David, using ./bin/path-tracer David, I got segmentation fault at line 277 in objects.cpp:
glm::vec3 averaged_normal = (normals[fx - 1] + normals[fy - 1] + normals[fz - 1]) / 3.0f;
the size of normal is 24 but fx ,fy ,fz is 167, 0 and 72 for the test case I'm running.

I'm not sure if there's anything wrong with the fx, fy, fz value read from the file is wrong, or why the value will exceed size of normal.

**Comment by amanshenoy** [comment]
Hey, it might be the case that the parser did not parse the normals from the obj properly. You could try setting evaluate normals as true to see if the problem persists.
